[package]
name = "const-tweaker-attribute"
version = "0.1.0"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.16"
darling = "0.10.2"
proc-macro2 = "1.0.9"
quote = "1.0.3"
